version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          profile-name: default
      - run: |
          export DOCKER_TAG="$CIRCLE_BRANCH-$CIRCLE_SHA1"
          export DOCKER_IMAGE="vfeskov/gitpunch:$DOCKER_TAG"

          docker build -t $DOCKER_IMAGE .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push $DOCKER_IMAGE

          ./.circleci/deploy-docker-image.sh

workflows:
  aws-cli:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - deploy-circleci
